# Generated by Django 4.1.2 on 2022-11-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0027_rename_uploaded_by_translation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glossary',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
