# Generated by Django 4.1.3 on 2023-01-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0030_alter_translation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entry',
            name='target',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='translation',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
