# Generated by Django 4.1.3 on 2023-07-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0033_alter_segment_source_alter_segment_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='job_number',
            new_name='title',
        ),
    ]
