# Generated by Django 4.1.3 on 2023-07-14 08:53

from django.db import migrations


def add_glossaries_as_resources(apps, schema_editor):

    Glossary = apps.get_model("archive", "Glossary")
    Resource = apps.get_model("archive", "Resource")

    for glossary in Glossary.objects.all():
        resource = Resource(
            resource_type="GLOSSARY",
            title=glossary.title,
            notes=glossary.notes,
            created_on=glossary.created_on,
            created_by=glossary.created_by,
            updated_on=glossary.updated_on,
            updated_by=glossary.updated_by,
        )
        resource.save()


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0035_resource_item"),
    ]

    operations = [
        migrations.RunPython(add_glossaries_as_resources)
    ]
