# Generated by Django 4.1.3 on 2023-07-15 01:04

from django.db import migrations


def add_entries_as_items(apps, schema_editor):

    Entry = apps.get_model("archive", "Entry")
    Item = apps.get_model("archive", "Item")
    Resource = apps.get_model("archive", "Resource")

    for entry in Entry.objects.all():
        resource = Resource.objects.get(title=entry.glossary.title)
        item = Item(
            resource=resource,
            source=entry.source,
            target=entry.target,
            notes=entry.notes,
            created_on=entry.created_on,
            created_by=entry.created_by,
            updated_on=entry.updated_on,
            updated_by=entry.updated_by,
        )
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0037_auto_20230714_1829"),
    ]

    operations = [
        migrations.RunPython(add_entries_as_items)
    ]
