# Generated by Django 4.1.3 on 2023-07-15 02:10

from django.db import migrations


def add_segments_as_items(apps, schema_editor):

    Item = apps.get_model("archive", "Item")
    Segment = apps.get_model("archive", "Segment")
    Resource = apps.get_model("archive", "Resource")

    for segment in Segment.objects.all():
        resource = Resource.objects.get(title=segment.translation.title)
        item = Item(
            resource=resource,
            source=segment.source,
            target=segment.target,
            created_on=resource.created_on,
            created_by=resource.created_by,
            updated_on=resource.updated_on,
            updated_by=resource.updated_by,
        )
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0038_auto_20230715_1004"),
    ]

    operations = [
        migrations.RunPython(add_segments_as_items)
    ]
