# Generated by Django 3.2.6 on 2021-09-23 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_entry_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='glossary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='resources.glossary'),
        ),
    ]
