# Generated by Django 3.2.11 on 2022-01-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_entry_glossary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glossaryuploadfile',
            old_name='glossary_title',
            new_name='glossary_name',
        ),
    ]
