# Generated by Django 3.2.11 on 2022-01-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_glossary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='glossaryuploadfile',
            name='glossary_name',
            field=models.CharField(max_length=70),
        ),
    ]
