# Generated by Django 3.2.11 on 2022-02-18 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0009_auto_20220116_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_glossaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_glossaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
