# Generated by Django 3.2.11 on 2022-02-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_auto_20220218_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
