# Generated by Django 3.2.11 on 2022-02-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_glossary_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossary',
            options={'ordering': ['title'], 'verbose_name': 'glossary', 'verbose_name_plural': 'glossaries'},
        ),
    ]
