# Generated by Django 4.0.5 on 2022-06-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_field_alter_translation_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='client',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='translation',
            name='field',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
