# Generated by Django 4.0.5 on 2022-06-17 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_alter_translation_client_alter_translation_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='translation_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tmx'], message=['Please select a file having a ".tmx" file extension.'])])),
                ('job_number', models.CharField(max_length=70)),
                ('field', models.CharField(max_length=70)),
                ('client', models.CharField(max_length=70)),
                ('glossary_notes', models.TextField()),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Translation file',
                'verbose_name_plural': 'Translation files',
            },
        ),
    ]
