# Generated by Django 4.0.5 on 2022-06-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0019_alter_translationuploadfile_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationuploadfile',
            old_name='glossary_notes',
            new_name='notes',
        ),
    ]
