# Generated by Django 4.0.5 on 2022-06-17 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_rename_glossary_notes_translationuploadfile_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='translation_file',
            field=models.FileField(null=True, upload_to='translation_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tmx'], message=['Please select a file with a ".tmx" file extension.'])]),
        ),
    ]
