# Generated by Django 4.0.5 on 2022-06-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_translation_translation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='client',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='translation',
            name='field',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
