# Generated by Django 4.0.5 on 2022-06-18 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_alter_translation_client_alter_translation_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslationUploadFile',
        ),
        migrations.AddField(
            model_name='glossary',
            name='glossary_file',
            field=models.FileField(null=True, upload_to='glossary_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'], message=['Please select a file having a ".txt" file extension.'])]),
        ),
    ]
