# Generated by Django 4.0.5 on 2022-06-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_delete_translationuploadfile_glossary_glossary_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlossaryUploadFile',
        ),
        migrations.AlterField(
            model_name='glossary',
            name='glossary_file',
            field=models.FileField(null=True, upload_to='glossary_files'),
        ),
    ]
