# Generated by Django 4.1.2 on 2022-10-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_alter_translation_translation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='translator',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
