# Generated by Django 4.1.2 on 2022-11-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0026_translation_translator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='uploaded_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='uploaded_on',
            new_name='created_on',
        ),
    ]
