# Generated by Django 4.1.3 on 2023-01-18 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0029_alter_glossary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_translations', to=settings.AUTH_USER_MODEL),
        ),
    ]
