# Generated by Django 4.1.3 on 2023-01-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0031_alter_entry_source_alter_entry_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='translation',
            name='client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='job_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translator',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
